export const ACTIONS = {
  CONNECT: "CONNECT_TO_SOCKET",
  DISCONNECT: "DISCONNECT_SOCKET",
  CONNECTION_SUCCESS: "CONNECTION_SUCCESS",
  ORDER_BOOK_DATA: "ORDER_BOOK_DATA",
  SUBSCRIBED_SUCCESSFULLY: "SUBSCRIBED_SUCCESSFULLY",
  CHANGE_PRECISION: "CHANGE_PRECISION",
};
